pref("extensions.{5C655500-E712-41e7-9349-CE462F844B19}.description", "chrome://translator/locale/translator.properties");
pref('extensions.translator._debug', false);
pref('extensions.translator.enabled', true);
pref('extensions.translator.toolbar', false);
pref('extensions.translator.status.icon', true);
pref('extensions.translator.context.menu', true);
pref('extensions.translator.language.source', 'auto');
pref('extensions.translator.language.target', 'en');
pref('extensions.translator.languages.selected', 'af,sq,ar,be,bg,ca,zh,zh-CN,zh-TW,hr,cs,da,nl,en,et,tl,fi,fr,gl,de,el,iw,ht,hi,hu,is,id,ga,it,ja,ko,lv,lt,mk,ms,mt,no,fa,pl,pt,pt-PT,ro,ru,sr,sk,sl,es,sw,sv,th,tr,uk,vi,cy,yi');
pref('extensions.translator.translate.selection', false);
pref('extensions.translator.translate.button', true);
pref('extensions.translator.hotkey.translate', true);
pref('extensions.translator.hotkey.translate.modifiers', 'control alt');
pref('extensions.translator.hotkey.translate.key', 'T');
pref('extensions.translator.hotkey.input', true);
pref('extensions.translator.hotkey.input.modifiers', 'control alt');
pref('extensions.translator.hotkey.input.key', 'Q');
pref('extensions.translator.hotkey.page', true);
pref('extensions.translator.hotkey.page.modifiers', 'control alt');
pref('extensions.translator.hotkey.page.key', 'P');
pref('extensions.translator.theme', 'default');
pref('extensions.translator.autocopy', false);